name: Databricks Bundle Validation

on:
  pull_request:
    branches:
      - main-2

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v0

      - name: Validate Databricks Bundle
        working-directory: ./day_9_Q_6_bundle/my_project
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle validate